---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role vhost
# 

#
# vars are namespaced with the module name.
#
vhost_role_name: vhost

#
# OS packages
#

vhost_debian_pkgs: []

vhost_redhat_pkgs: []
