---

- name: install jenkins analytics extra system packages
  apt:
    pkg={{ item }} state=present update_cache=yes
  with_items: JENKINS_ANALYTICS_EXTRA_PKGS
  tags:
  - jenkins

- fail: msg=included unix realm by accident
  when: jenkins_auth_realm.name != "unix"
  tags:
    - jenkins-auth

- fail: msg=Please change default password for jenkins user
  when: jenkins_auth_realm.plain_password == 'jenkins'
  tags:
    - jenkins-auth

- name: Install httplib2 (required by uri module used in this role)
  pip:
    name: httplib2

- name: generate jenkins user password
  shell: "openssl passwd -1 '{{ jenkins_auth_realm.plain_password | quote }}'"
  register: jenkins_user_password_hash
  no_log: True
  tags:
    - jenkins-auth

- user:
    name: "{{ jenkins_user }}"
    state: present
    groups: shadow
    append: yes
    password: "{{ jenkins_user_password_hash.stdout }}"
  tags:
    - jenkins-auth

- name: template config.xml
  template:
    src: jenkins.config.main.xml
    dest: "{{ jenkins_home }}/config.xml"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  tags:
    - jenkins-auth

# Unconditionally restart Jenkins, this has two side-effects:
# 1. Jenkins uses new auth realm
# 2. We guarantee that jenkins is started (this is not certain
#    as Jenkins is started by handlers from jenkins_master,
#    these handlers are launched after this role).

- name: restart Jenkins
  service: name=jenkins state=restarted
  tags:
    - jenkins-auth

# Upload Jenkins credentials

- name: create credentials dir
  file: name={{ jenkins_credentials_root }} state=directory
  tags:
    - jenkins-auth

- name: upload groovy script
  template:
    src: addCredentials.groovy
    dest: "{{ jenkins_credentials_script }}"
    mode: "600"
  tags:
    - jenkins-auth

- name: upload credentials file
  template:
    src: credentials_file.json.j2
    dest: "{{ jenkins_credentials_file_dest }}"
    mode: "600"
    owner: "{{ jenkins_user }}"
  tags:
    - jenkins-auth

- name: add credentials
  include: execute_jenkins_cli.yaml
  vars:
    jenkins_command_string: "groovy {{ jenkins_credentials_script }}"
  tags:
    - jenkins-auth

- name: clean up
  file: name={{ jenkins_credentials_root }} state=absent
  tags:
    - jenkins-auth

# Upload seed job

- name: upload job file
  template: src=seed_job_template.xml dest=/tmp/{{ jenkins_seed_job.name }} mode="600"
  tags:
    - create-seed-job

- name: check if job is present
  include: execute_jenkins_cli.yaml
  vars:
    jenkins_command_string: "get-job {{ jenkins_seed_job.name }}"
    jenkins_ignore_cli_errors: yes
  tags:
    - create-seed-job

- set_fact:
    get_job_output: "{{ jenkins_command_output }}"
  tags:
    - create-seed-job

# Upload seed job to Jenkins

- name: Create seed job if absent
  include: execute_jenkins_cli.yaml
  vars:
    jenkins_command_string: "create-job {{ jenkins_seed_job.name }}"
    jenkins_command_prefix: "cat /tmp/{{ jenkins_seed_job.name }} | "
  when: get_job_output.rc != 0
  tags:
    - create-seed-job

- name: update seed job
  include: execute_jenkins_cli.yaml
  vars:
    jenkins_command_string: "update-job {{ jenkins_seed_job.name }}"
    jenkins_command_prefix: "cat /tmp/{{ jenkins_seed_job.name }} | "
  when: get_job_output.rc == 0
  tags:
    - create-seed-job

# Build the seed job

- name: Build the seed job
  include: execute_jenkins_cli.yaml
  vars:
    jenkins_command_string: "build {{ jenkins_seed_job.name }} -s"
  tags:
    - create-seed-job
