- name: Deploy analytics related services (except the pipeline)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    disable_edx_services: false
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
  roles:
    - aws
    - mysql
    - edxlocal
    - analytics_api
    - role: nginx
      nginx_sites:
        - insights
    - insights
